from tensorflow.keras.optimizers import Adam, RMSprop, SGD

MAX_SEQ_LENGTH = 37
EMBEDDING_SIZE = 300

RNN_UNITS = 128
TRAINABLE_EMBEDDINGS = True
LAYERS = ['bilstm']
MASK_ZERO = True
ACTIVATION = 'tanh'
RECURRENT_ACTIVATION = 'sigmoid'
DROPOUT = 0.4
RECURRENT_DROPOUT = 0.3
RETURN_SEQUENCES = True
OPTIMIZER = Adam
LEARNING_RATE = 0.001
LOSS = 'categorical_crossentropy'

BATCH_SIZE = 64
EPOCHS = 20
VAL_SPLIT = 0.15




TAGSETS_USED = ['ADJECTIVE', 'ADVERB', 'CONJUNCTION', 'DETERMINER', 'INTERJECTION', 'NOUN', 'NUMERAL', 'PARTICLE', 'PRONOUN', 'POSTPOSITION', 'PREPOSITION', 'PUNCTUATION', 'SYMBOL', 'VERB', 'RESIDUAL', 'AUXILIARY', 'COMPOUND']
